title: "gh-commit-ledger"
description: "gh-commit-ledger"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/gh-commit-ledger
plugins:
  - jekyll-sitemap
